# This workfow shows how to build a Docker image, tag and push it to
# DigitalOcean Container Registry. For more on the entire workflow, see
# www.digitalocean.com/docs/kubernetes/how-to/deploy-using-github-actions.

name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up vars used for tag
      - name: Set up Git variables
        run: |
          echo "DATE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Set up Docker Buildx (for better cross-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Install doctl to simplify digitalocean actions.
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          TAG="${{ env.DATE_TAG }}-${{ env.GIT_SHA }}" docker compose -f docker-compose.yaml build

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200

      - name: Push Docker image
        run: |
          TAG="${{ env.DATE_TAG }}-${{ env.GIT_SHA }}" docker compose -f docker-compose.yaml push
